
$image = Anya.jpg
$background = rgba(19120cff)

$image = Anya.jpg
$error = rgba(ffb4abff)

$image = Anya.jpg
$error_container = rgba(93000aff)

$image = Anya.jpg
$inverse_on_surface = rgba(372f28ff)

$image = Anya.jpg
$inverse_primary = rgba(865319ff)

$image = Anya.jpg
$inverse_surface = rgba(efe0d5ff)

$image = Anya.jpg
$on_background = rgba(efe0d5ff)

$image = Anya.jpg
$on_error = rgba(690005ff)

$image = Anya.jpg
$on_error_container = rgba(ffdad6ff)

$image = Anya.jpg
$on_primary = rgba(4a2800ff)

$image = Anya.jpg
$on_primary_container = rgba(ffdcbfff)

$image = Anya.jpg
$on_primary_fixed = rgba(2d1600ff)

$image = Anya.jpg
$on_primary_fixed_variant = rgba(6a3c01ff)

$image = Anya.jpg
$on_secondary = rgba(412c18ff)

$image = Anya.jpg
$on_secondary_container = rgba(ffdcbfff)

$image = Anya.jpg
$on_secondary_fixed = rgba(291806ff)

$image = Anya.jpg
$on_secondary_fixed_variant = rgba(59422dff)

$image = Anya.jpg
$on_surface = rgba(efe0d5ff)

$image = Anya.jpg
$on_surface_variant = rgba(d5c3b6ff)

$image = Anya.jpg
$on_tertiary = rgba(2b340fff)

$image = Anya.jpg
$on_tertiary_container = rgba(dde8b4ff)

$image = Anya.jpg
$on_tertiary_fixed = rgba(171e00ff)

$image = Anya.jpg
$on_tertiary_fixed_variant = rgba(414b24ff)

$image = Anya.jpg
$outline = rgba(9e8e81ff)

$image = Anya.jpg
$outline_variant = rgba(51443aff)

$image = Anya.jpg
$primary = rgba(fdb876ff)

$image = Anya.jpg
$primary_container = rgba(6a3c01ff)

$image = Anya.jpg
$primary_fixed = rgba(ffdcbfff)

$image = Anya.jpg
$primary_fixed_dim = rgba(fdb876ff)

$image = Anya.jpg
$scrim = rgba(000000ff)

$image = Anya.jpg
$secondary = rgba(e2c0a4ff)

$image = Anya.jpg
$secondary_container = rgba(59422dff)

$image = Anya.jpg
$secondary_fixed = rgba(ffdcbfff)

$image = Anya.jpg
$secondary_fixed_dim = rgba(e2c0a4ff)

$image = Anya.jpg
$shadow = rgba(000000ff)

$image = Anya.jpg
$source_color = rgba(b38559ff)

$image = Anya.jpg
$surface = rgba(19120cff)

$image = Anya.jpg
$surface_bright = rgba(403830ff)

$image = Anya.jpg
$surface_container = rgba(261e18ff)

$image = Anya.jpg
$surface_container_high = rgba(312822ff)

$image = Anya.jpg
$surface_container_highest = rgba(3c332cff)

$image = Anya.jpg
$surface_container_low = rgba(211a14ff)

$image = Anya.jpg
$surface_container_lowest = rgba(130d07ff)

$image = Anya.jpg
$surface_dim = rgba(19120cff)

$image = Anya.jpg
$surface_tint = rgba(fdb876ff)

$image = Anya.jpg
$surface_variant = rgba(51443aff)

$image = Anya.jpg
$tertiary = rgba(c1cc99ff)

$image = Anya.jpg
$tertiary_container = rgba(414b24ff)

$image = Anya.jpg
$tertiary_fixed = rgba(dde8b4ff)

$image = Anya.jpg
$tertiary_fixed_dim = rgba(c1cc99ff)

