-- Hyprland Lua config (replaces hyprland.conf since 0.55+)
-- https://wiki.hypr.land/Configuring/Start/
-- hyprland.conf and friends (*.conf) are kept in this folder for reference,
-- but are ignored by Hyprland once this file exists.

require("hyprland.env")
require("hyprland.monitors")
require("hyprland.general")
require("hyprland.keybinds")
require("hyprland.windowrules")
require("hyprland.execs")

-- Generated by matugen from the current wallpaper, see
-- ../../matugen/.config/matugen/templates/hyprland-colors.lua
require("hyprland.colors")
