-- Look and feel
-- https://wiki.hypr.land/Configuring/Basics/Variables/

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 9,

        border_size = 2,

        -- col.active_border / col.inactive_border are set from the current
        -- wallpaper colors in hyprland/colors.lua (generated by matugen)

        resize_on_border = false,

        -- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/
        allow_tearing = false,

        layout = "master",

        snap = {
            enabled = true,
            window_gap = 5,
        },
    },

    decoration = {
        rounding = 0,
        dim_inactive = false,
        dim_strength = 0.2,

        blur = {
            enabled = true,
            size = 3,
            passes = 3,
            ignore_opacity = true,
            xray = false,
            new_optimizations = true,
        },

        active_opacity = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            -- color is set from the current wallpaper colors in hyprland/colors.lua
        },
    },

    animations = {
        enabled = true,
    },
})

-- https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("myBezier", { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })

-- Old hyprlang "windows"/"fade" applied to both directions at once;
-- split into the *In/*Out leaves the Lua animation system expects.
hl.animation({ leaf = "windowsIn", enabled = true, speed = 7, bezier = "myBezier", style = "popin 80%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 7, bezier = "myBezier", style = "popin 80%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 7, bezier = "myBezier" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 7, bezier = "myBezier" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 6, bezier = "myBezier", style = "slidefade 80%" })

hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },

    master = {
        new_status = "slave",
    },

    misc = {
        animate_mouse_windowdragging = false,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        enable_swallow = true,
        swallow_regex = "^(alacritty|kitty)$",
    },

    debug = {
        vfr = true,
    },
})

-- https://wiki.hypr.land/Configuring/Basics/Variables/#input
hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
        },
    },

    gestures = {
        workspace_swipe_touch = false,
    },
})

-- Example per-device config (carried over unchanged; "epic-mouse-v1" is a
-- placeholder name from the default config, replace with your real device)
hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})
