cursor #efe0d5
cursor_text_color #d5c3b6

foreground            #efe0d5
background            #19120c
selection_foreground  #412c18
selection_background  #e2c0a4
url_color             #865319

# black
color0   #3c332c
color8   #312822

# red
color1   #ffb4ab
color9   #93000a

# green
color2   #fdb876
color10  #6a3c01

# yellow
color3   #e2c0a4
color11  #59422d

# blue
color4   #865319
color12  #fdb876

# magenta
color5   #c1cc99
color13  #414b24

# cyan
color6   #e2c0a4
color14  #ffdcbf

# white
color7    #efe0d5
color15   #d5c3b6
