cursor #efe0d5
cursor_text_color #d5c3b6

foreground            #efe0d5
background            #19120c
selection_foreground  #412c19
selection_background  #e2c0a5
url_color             #87521b

# black
color0   #3c332c
color8   #312822

# red
color1   #ffb4ab
color9   #93000a

# green
color2   #feb877
color10  #6b3b03

# yellow
color3   #e2c0a5
color11  #5a422d

# blue
color4   #87521b
color12  #feb877

# magenta
color5   #c2cb98
color13  #424a23

# cyan
color6   #e2c0a5
color14  #ffdcc0

# white
color7    #efe0d5
color15   #d5c3b6
